### ISSUE TITLE
Добрый день Автор

### ISSUE THREAD

**Issue by hbleid** [monkrel/WarHook#1]
Слышал о печальной новости о вашем покидании из ВарХук.
Лучше бы вы начали брать за это деньги чем уходите.
Вы оставили код открытым, мне как обычному пользователю очень интересно пользоваться читом и продолжать использовать его в личных целях.
Не могли бы вы подсказать, как делать обновления и какие строки менять. на простом языке. Так как я не программист.
Зарабатывать этим не планирую и перенимать вашу работу, интересно личное использование чита.
при обновлении комментария он изменяет текс и получается ерунда в обращении к вам.

**Comment by monkrel** [comment]
You can write in your native language

**Comment by hbleid** [comment]
Да могу. Но сайт сам сменил половину слов. Не могли бы вы научить делать
обновления на чит. Для личного пользования. Я уже не могу играть без вашего
Чита

пт, 20 янв. 2023 г., 17:55 monkrel ***@***.***>:
