### ISSUE TITLE
Game freezes/crashes on injection

### ISSUE THREAD

**Issue by fhuf** [monkrel/WarHook#11]
It worked just fine on the 6th, I don't know why it hasn't worked in the past two days. I'm too dumb to fix this issue through Cheat Engine, as I am not intelligent. Help a Script Kiddie out.

**Comment by fhuf** [comment]
War Thunder either freezes for 3-5 seconds on injection, forcing you to crash it to tab into other areas of your computer, or the game crashes instantly on injection. I was using Xenos Injector, I've tried different injectors and different testing environments, and I've found it's the DLL. (Warhook is found on the "cheater.fun" website in the form of a .dll file, Labeled as Warhook.dll)

**Comment by dongerlel** [comment]
just disable overlays like discord/afterburner
