### ISSUE TITLE
Mouse not working after new update

### ISSUE THREAD

**Issue by syrex1013** [monkrel/WarHook#12]
Hi,
After new update, mouse only works on cheat menu. After injecting, you can click on the options in cheat menu, but not on the WT interface.
Probably someting with window hooking?

**Comment by monkrel** [comment]
https://github.com/monkrel/WarHook/commit/20d1882b5b103e79ff0b25c67299eab7cf40d0b2

**Comment by syrex1013** [comment]
I mean, there is no way to click in war thunder. When I inject the dll, cheat menu pops up, but I can only click on things in it. I cant click on the button to start battle, and I can't click anywhere else.
