### ISSUE TITLE
WarHook not working

### ISSUE THREAD

**Issue by something-0001** [monkrel/WarHook#15]
I already left a statement on unknowncheats, however to reiterate, it will not work both from built fron source, and from the DLL provided in the unknowncheats thread.

That said, I've tried different types of injection, redownload Xenos all together, nothing. Note that EAC is off.

**Comment by monkrel** [comment]
Install dependencies
![image](https://user-images.githubusercontent.com/84017229/228793877-4c2e335d-72a1-4792-a347-9691dd27e50f.png)
![image](https://user-images.githubusercontent.com/84017229/228793988-5ee8fe47-4d68-4c7a-8013-6a997907001f.png)
Update drivers, DirectX
Maybe Windows problem

**Comment by dongerlel** [comment]
you are using other overlays like discord/msi after burner
those 100% break warhook. First inject the chair then use your desired overlay.
