### ISSUE TITLE
Warhook working....every now and then.

### ISSUE THREAD

**Issue by WayneDwane** [monkrel/WarHook#16]
So,most of the time the cheat will either not inject or will inject but i'd see that if you paid you we're scammed screen pop up for just a second and i'd go back to the usual war thunder garade. HOWEVER i can't click on anything and have to end the aces process. And very rarely it works just right,yknow the screen pops up i agree and i can use the insert button just fine.

Injectors: Extreme injector 3,Xenos,Process Hacker
OS:Windows 10
AV:Windows Defender/Windows Security (Disabled when injecting obviously)
Dependencies:Used this pc for quite some time and i've downloaded pretty much every dependency i could possibly think of

Should also note i play on windowed fullscreen,ULQ mode. ESP + Reload timer are the only 2 options i've ever enabled.
Thanks a lot for the cheat BTW. When it works,it's great.

**Comment by dongerlel** [comment]
compile the dll yourself using the newest code + disable ALL overlays before injecting(msi afterburmer, discord etc)
this chair is 100% functional using it for months now

**Comment by WayneDwane** [comment]
Okay,will do. Also,the chair?
