### ISSUE TITLE
Crash on injection

### ISSUE THREAD

**Issue by Cheesyburger69** [monkrel/WarHook#18]
So even when using extreme inject or xenos it crashes my game, I have had the cheat work before on multiple occasions however it has stopped working within the last weak due to the game constantly crashing as soon as it injects, it comes up with saying sucessful injection however the game gives me this. 
![crash](https://user-images.githubusercontent.com/129900443/229910061-b0337c16-46ef-493c-9c89-010290dcd5a9.PNG)
and 
![Capture](https://user-images.githubusercontent.com/129900443/229910093-06bac17e-2491-43e5-83c1-e40001964b77.PNG)
I have tried with full client version of the game as well nothing different happened EAC is off of course.

**Comment by Cheesyburger69** [comment]
Sent I am God Emperor man

**Comment by HeApCbC** [comment]
same problem happened on me, my dear sir, wt just crash after I inject dll, how could I do?

**Comment by HeApCbC** [comment]
how could I send my latest DMP file to you

**Comment by meiyuluohua** [comment]
The discord link is invalid

**Comment by monkrel** [comment]
> The discord link is invalid

Everything is correct
