### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by xdadova** [monkrel/WarHook#3]
1>Generating Code...
1>Done building project "WarHook.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:06,565 ==========
it built everything else but not this

**Comment by morganwall** [comment]
You need to include more of the error output, we can't tell anything from this.

**Comment by xdadova** [comment]
like what

**Comment by xdadova** [comment]
what else do i send

**Comment by xdadova** [comment]
that's literally all it gave to me
![image](https://user-images.githubusercontent.com/83107663/214019588-166fcfd3-21d8-4137-a729-b6e8bb653530.png)

**Comment by morganwall** [comment]
The VS Output???
Also it builds fine in Release | x64, this is a problem on your end and not with the project.

**Comment by xdadova** [comment]
ok i don't want to send the ENTIRE output but everything was going fine until this

**Comment by morganwall** [comment]
Spend sometime to actually learn what you're doing, rather than begging for someone to teach you to compile a VS project.

**Comment by xdadova** [comment]
1 i wasn't begging
2 i never said this is a problem with the project i know it's a problem on my end dumbass
3 yes i am new there are so many tutorials on how to learn how to compile but none of them say about any possible errors

**Comment by morganwall** [comment]
You were, not on here, but on UC.
And there are plenty of resources on compliling.

Fuck off skid.

**Comment by morganwall** [comment]
@monkrel Please close this issue as it's not an issue with the repo. ty

**Comment by xdadova** [comment]
so instead of helping me like a normal person you curse me, call me a skid and don't explain anything to me you're a disgrace and probably have mental issues

**Comment by morganwall** [comment]
Are you stupid? You called me a "dumbass".
Go cry somewhere else cos you're too incompetent to simple compile something.

**Comment by xdadova** [comment]
![image](https://user-images.githubusercontent.com/83107663/214021516-9aaaed2d-7583-412c-be87-2f092f5819e1.png)
was blockhead a better term?

**Comment by hbleid** [comment]
товарищ админ. Объясните как делать обновления простым людям, тем кто не соображает в кодировании, просто какие значения менять что бы играть дальше

**Comment by xdadova** [comment]
@morgalwall as far as i understand Cyrillic he said i don't understand coding and i need support on this

**Comment by xdadova** [comment]
maybe it's my build tools?

**Comment by xdadova** [comment]
yep it was

**Comment by xdadova** [comment]
@morganwall thank you for the help retard

**Comment by hbleid** [comment]
кто нибудь обьяснит как не программистам для себя обновлять вархук?

**Comment by xdadova** [comment]
> кто нибудь обьяснит как не программистам для себя обновлять вархук?

There is a thread on unknowncheats where people share their code
