### ISSUE TITLE
How do you search for data's address？

### ISSUE THREAD

**Issue by 00ffcc** [monkrel/WarHook#4]
I try to get enemy players' position and velocity through Cheat Engine but failed. I could only get local player's data. Could you please tell me how to search for data's address in memory? I want to get the offset of velocity, which is approved to be accessible in [another hack](https://github.com/monkrel/WarHook).

**Comment by monkrel** [comment]
Use this thread: [https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/85949-war-thunder.html](url) 
ground vel= Unit+1d98+54
If you use my CT table - update every offset to newest one by finding signature

**Comment by 00ffcc** [comment]
> Use this thread: [https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/85949-war-thunder.html](url) ground vel= Unit+1d98+54 If you use my CT table - update every offset to newest one by finding signature

thank you sir, but the offset seems do not work on plane🤔

**Comment by monkrel** [comment]
> > Use this thread: [https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/85949-war-thunder.html](url) ground vel= Unit+1d98+54 If you use my CT table - update every offset to newest one by finding signature
> 
> thank you sir, but the offset seems do not work on plane🤔

Should be
`vel for plane = 0x9F8+ 0x31C8`

**Comment by 00ffcc** [comment]
> > > Use this thread: [https://www.unknowncheats.me/forum/other-mmorpg-and-strategy/85949-war-thunder.html](url) ground vel= Unit+1d98+54 If you use my CT table - update every offset to newest one by finding signature
> > 
> > 
> > thank you sir, but the offset seems do not work on plane🤔
> 
> Should be `vel for plane = 0x9F8+ 0x31C8`

do you mean unit+0x9F8+0x31C8? I could only get (0,0,0) from this offset.😥

**Comment by monkrel** [comment]
Idk, it was 20th December
![image](https://user-images.githubusercontent.com/84017229/214632718-0dd06065-be5c-4585-a56e-f25738dec245.png)

**Comment by 00ffcc** [comment]
lol,the date of last major update is 20th December😥,so the offset is incorrect. I managed to find the address of velocity but the address is before unit? have you ever seen this situation? 🥲what should I do?
