### ISSUE TITLE
error loading the solution : HRESULT E_FAIL

### ISSUE THREAD

**Issue by Enclave92** [monkrel/WarHook#5]
Hello, 

first of all thank you for uploading the source , as i'm trying to learn and also help u update it.

but sadly somehow i cannot open the solution with VS2019 , it show the error HRESULT E_FAIL , what to do ?

**Comment by monkrel** [comment]
The following solution worked for me:

- Close Visual Studio.
- Go to the project's root folder and delete the .vs directory.
- Start Visual Studio and open the solution.
- The build should now work.

from [https://stackoverflow.com/questions/13361199/error-hresult-e-fail-has-been-returned-from-a-call-to-a-com-component-vs2012-whe](stackoverflow) btw

**Comment by Enclave92** [comment]
thanks Monkrel, the solution is starting like a charm.
