### ISSUE TITLE
Updating sigs and compiling errors

### ISSUE THREAD

**Issue by Enclave92** [monkrel/WarHook#6]
Hello,

Edit:  ignored the "std::format" and "char8_t undefined" errors and still compiled and it worked.

i'm willing to keep this project alive and commit to updating it , but due to lack of knowledge as i'm a newbie of c++ (i code in vb.net/html/css) , i'm having a hard time .

if you could help pointing me to the right direction for the first time , then i'll do it on my own and keep it alive , here are the data using your Cheat engin  file : 

![image](https://user-images.githubusercontent.com/116391607/216391966-36c989bb-9a78-43a5-991e-e72e044845b2.png)

if i read the code correctly , i assume i should update the content of warhook/sigs.h (or should i update offsets[0] ?  , however i don't know where to find the same format of data you use.

thanks in advance mate.

**Comment by monkrel** [comment]
If something broke - you need to check sigs. If sigs work fine - then some of classes broken.
