### ISSUE TITLE
how i use it

### ISSUE THREAD

**Issue by kimi1233212** [monkrel/WarHook#9]

**Comment by monkrel** [comment]
Build it as Release/x64 and inject DLL into the game

**Comment by kimi1233212** [comment]
it dont let me inject

**Comment by kimi1233212** [comment]
do you have discord some thing

**Comment by kimi1233212** [comment]
![image](https://user-images.githubusercontent.com/110891929/221577079-32b23acb-985f-4203-8e74-7bb69f65fe4b.png)

**Comment by kimi1233212** [comment]
another injector
![image](https://user-images.githubusercontent.com/110891929/221577576-6bce8d4f-fce2-4d6f-912b-f1b2b68c838a.png)

**Comment by monkrel** [comment]
Disable EAC

**Comment by monkrel** [comment]
Click on "Start Manual Game update" when you try to start game thru steam and disable it in launcher

**Comment by kimi1233212** [comment]
it now allow to play real battle? bc it need anti cheat

**Comment by monkrel** [comment]
ofc it's not. make a bypass and play RB🙄

**Comment by kimi1233212** [comment]
bruh how i am really noob bro and sorry for asking to much-.-

**Comment by kimi1233212** [comment]
How I bypass

**Comment by monkrel** [comment]
It's not for me with questions like that

**Comment by kimi1233212** [comment]
bruh

**Comment by kimi1233212** [comment]
i really donw know how can you teach me

**Comment by kimi1233212** [comment]
like it dont work with cheat engine and xeon and ext

**Comment by monkrel** [comment]
Of course not. Anti-cheat and is made in order to prevent you from penetrating into the memory of the game. I don't bypass anti-cheats and I can't teach it. To do this, you need to write your driver, look in this direction

**Comment by kimi1233212** [comment]
i dont even know how to type code

**Comment by kimi1233212** [comment]
did this videos teach work ? bc i just got stuck in some step
https://www.youtube.com/watch?v=_auePp1nTHs&t=1204s
